# @package _global_
datamodule:
  train_data_source:
    image_clip_ids: [ -12, -8, -4, 0 ]
    bbox_clip_ids: [ 0, 4 ]
  val_data_source:
    image_clip_ids: [ -12, -8, -4, 0 ]
    bbox_clip_ids: [ 4 ]
  test_data_source:
    image_clip_ids: [ -12, -8, -4, 0 ]
    bbox_clip_ids: [ 4 ]

model:
  metric:
    future_time_constant: [4]

sap_strategy:
  past_length: 4
  future_length: 1
