# @package _global_
datamodule:
  train_data_source:
    image_clip_ids: [ -3, -2, -1, 0 ]
    bbox_clip_ids: [ 0, 16 ]
  val_data_source:
    image_clip_ids: [ -3, -2, -1, 0 ]
    bbox_clip_ids: [ 16 ]
  test_data_source:
    image_clip_ids: [ -3, -2, -1, 0 ]
    bbox_clip_ids: [ 16 ]

model:
  metric:
    future_time_constant: [16]

sap_strategy:
  past_length: 4
  future_length: 1
