# @package _global_
datamodule:
  train_data_source:
    image_clip_ids: [ -6, -4, -2, 0 ]
    bbox_clip_ids: [ 0, 2 ]
  val_data_source:
    image_clip_ids: [ -6, -4, -2, 0 ]
    bbox_clip_ids: [ 2 ]
  test_data_source:
    image_clip_ids: [ -6, -4, -2, 0 ]
    bbox_clip_ids: [ 2 ]

model:
  metric:
    future_time_constant: [2]

sap_strategy:
  past_length: 4
  future_length: 1
