# @package _global_
datamodule:
  train_data_source:
    image_clip_ids: [ -8, -4, -2, -1, 0]
    bbox_clip_ids: [ 1, 2, 4, 8 ]
  val_data_source:
    image_clip_ids: [ -8, -4, -2, -1, 0]
    bbox_clip_ids: [ 1, 2, 4, 8 ]
  test_data_source:
    image_clip_ids: [ -8, -4, -2, -1, 0]
    bbox_clip_ids: [ 1, 2, 4, 8 ]

model:
  metric:
    future_time_constant: [ 1, 2, 4, 8 ]

sap_strategy:
  past_length: 5
  future_length: 4
