# @package _global_
datamodule:
  train_data_source:
    image_clip_ids:
      - [ -24, -16, -8, 0]
      - [ -12, -8, -4, 0 ]
      - [ -6, -4, -2, 0 ]
      - [ -3, -2, -1, 0 ]
    bbox_clip_ids:
      - [ 0, 8 ]
      - [ 0, 4 ]
      - [ 0, 2 ]
      - [ 0, 1 ]
  val_data_source:
    image_clip_ids: [ -3, -2, -1, 0 ]
    bbox_clip_ids: [ 1 ]
  test_data_source:
    image_clip_ids: [ -3, -2, -1, 0 ]
    bbox_clip_ids: [ 1 ]

model:
  metric:
    future_time_constant: [1]

sap_strategy:
  past_length: 4
  future_length: 1
