name: ts

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip==24.0

  - pip:
      - -r requirements-pytorch.txt -i https://mirrors.nju.edu.cn/pytorch/whl/cu121
      - -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
