defaults:
  - detr_l
  - _self_

backbone:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True
neck:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
head:
  num_layers: 3
  num_points: [1, 1, 1]
