defaults:
  - longshortnet_s
  - _self_

backbone:
  base_depth: 2
  base_channel: 48
neck:
  in_channels: [192, 384, 768]
  remap: False
  residue: False
head:
  in_channels: ${model.neck.in_channels}
  mid_channel: 192
  conf_thre: 0.01
  nms_thre: 0.65
  gamma: 1.0
  ignore_thr: 0.4
  ignore_value: 1.7
