# @package _global_

defaults:
  - _self_
  - datamodule: dummy
  - model: dummy
  - optional sap_strategy: null
  - speed: null
  - callbacks:
    - model_summary
    - tqdm_progress_bar
  - loggers:
    - tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
