from .rtdetrv2_decoder import RTDETRTransformerv2


class AdaptiveRTDETRTransformer(RTDETRTransformerv2):
    def __init__(self,
                 num_classes=80,
                 hidden_dim=256,
                 num_queries=300,
                 feat_channels=[512, 1024, 2048],
                 feat_strides=[8, 16, 32],
                 num_levels=3,
                 num_points=4,
                 nhead=8,
                 num_layers=6,
                 dim_feedforward=1024,
                 dropout=0.,
                 activation="relu",
                 num_denoising=100,
                 label_noise_ratio=0.5,
                 box_noise_scale=1.0,
                 learn_query_content=False,
                 eval_spatial_size=None,
                 eval_idx=-1,
                 eps=1e-2,
                 aux_loss=True,
                 cross_attn_method='default',
                 query_select_method='default'):
        super().__init__(
            num_classes,
            hidden_dim,
            num_queries,
            feat_channels,
            feat_strides,
            num_levels,
            num_points,
            nhead,
            num_layers,
            dim_feedforward,
            dropout,
            activation,
            num_denoising,
            label_noise_ratio,
            box_noise_scale,
            learn_query_content,
            eval_spatial_size,
            eval_idx,
            eps,
            aux_loss,
            cross_attn_method,
            query_select_method,
        )

