# Same as `code-quality-pr.yaml` but triggered on commit to main branch
# and runs on all files (instead of only the changed ones)

name: Code Quality Main

on:
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.13"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Run pre-commits
        uses: pre-commit/action@v2.0.3
